### ISSUE TITLE
dependencia 'account_chart'

### ISSUE THREAD

**Issue by efarias** [bmya/odoo-bmya-cl#6]
Hola, he intentado instalar el módulo l10n_cl_chart, pero aparece una dependencia 'account_chart' que ya no se encuentra en la carpeta addons de Odoo V9.

**Comment by Danisan** [comment]
Este es un  repositorio para hacer merge mediante subtree. Por lo tanto no aceptamos issues ni pull requests en este repo.
Voy a cerrar el issue, para que lo crees en github.com/odoo-chile en el módulo que corresponde (l10n_cl_chart en este caso)

**Comment by Danisan** [comment]
E Farias, por favor, pruébalo ya que hemos removido las dependencias. Espero comentarios.

**Comment by Danisan** [comment]
Estimado, gracias por avisar. 
Por ahora no estamos actualizando la 9... espero en breve poder hacerlo, pero estamos trabajando fuerte sobre la 8.
Incluyo las recomendaciones de colaboración.
http://www.odoochile.org/blog/novedades-1/post/principios-para-colaborar-en-github-1#blog_content
