### ISSUE TITLE
Problema en requirements.txt

### ISSUE THREAD

**Issue by Cu4rach4** [bmya/odoo-bmya-cl#8]
Hola, al ejecutar pip install -r requirements.txt da el siguiente error:

`sudo pip install -r requirements.txt 
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting urllib2 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement urllib2 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for urllib2 (from -r requirements.txt (line 1))`

La plataforma es: 

Linux version 4.4.0-45-generic (buildd@lgw01-34) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016

Gracias!!

**Comment by Danisan** [comment]
Idem respuesta anterior, en https://github.com/odoo-chile/l10n_cl_account_vat_ledger/issues/2

Por favor, observa que no aceptamos issues y commits en este repositorio.
